name: encacap-re-acbuilding

services:
  acbuilding-prod:
    container_name: encacap-re-acbuilding-prod
    image: encacap/re-acbuilding:stable
    ports:
      - 3012:3000
    env_file:
      - .env.production
    environment:
      - NEXT_PUBLIC_RE_ACB_API_URL=http://api-prod:3011
    networks:
      - encacap-re-network
    restart: unless-stopped

networks:
  encacap-re-network:
    external: true
    driver: bridge
