version: "3.9"
name: encacap-re-acbuilding

services:
  acbuilding:
    container_name: encacap-re-acbuilding
    build:
      context: ../../.
      dockerfile: ./.docker/prod/Dockerfile
      target: prod
    image: encacap-re-acbuilding
    ports:
      - 3012:3000
    env_file:
      - ../../.env.production
    environment:
      - NEXT_PUBLIC_RE_ACB_API_URL=http://encacap-re-api:3011
    networks:
      - encacap-re-network

networks:
  encacap-re-network:
    external: true
    driver: bridge
